apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi-server
  name: fastapi-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-server-pod
  template:
    metadata:
      labels:
        app: fastapi-server-pod
    spec:
      containers:
        - name: fastapi-server
          image: '{{ .Values.fastapi_server.containerImage }}'
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-server
  name: fastapi-server
spec:
  type: NodePort
  selector:
    app: fastapi-server-pod
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30007
